redraw_delay=0.1
font='Sarasa Mono J Nerd Font'
font_mono='Sarasa Mono J Nerd Font'
border_size=1
border_color='#FF000000'
font_size=14
plot_bg_border_color='#FF000000'
plot_bg_color='#FF000000'
plot_color=FFFFFF
