# Anime4K (High-end dGPU Presets)
Ctrl+0 no-osd change-list glsl-shaders clr ""; show-text "GLSL: Disabled"
Ctrl+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "GLSL: Anime4K Mode A (HQ)"
Ctrl+2 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "GLSL: Anime4K Mode A+A (HQ)"
# Ctrl+2 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "Anime4K: Mode B (HQ)"
# Ctrl+3 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "Anime4K: Mode C (HQ)"
# Ctrl+5 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "Anime4K: Mode B+B (HQ)"
# Ctrl+6 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "Anime4K: Mode C+A (HQ)"
Ctrl+3 no-osd change-list glsl-shaders set "~~/shaders/ArtCNN_C4F16.glsl"; show-text "GLSL: ArtCNN Conv4 Filter16 (MQ)"
Ctrl+4 no-osd change-list glsl-shaders set "~~/shaders/ArtCNN_C4F32.glsl"; show-text "GLSL: ArtCNN Conv4 Filter32 (HQ)"

# Audio
+ add audio-delay 0.010 # change A/V sync by delaying the audio
- add audio-delay -0.010 # change A/V sync by shifting the audio earlier
Ctrl++ ignore
Ctrl+- ignore

# Loop
l cycle-values loop-file "inf" "no" # toggle infinite file looping
L ab-loop # set/clear A-B loop points

# Speed
[ add speed -0.05 # decrease the playback speed
] add speed 0.05 # increase the playback speed
Ctrl+| no-osd af toggle @pitchrb; show-text "Pitch: Toggle Pitch Change Filter"
Shift+Ctrl+BS no-osd af-command pitchrb set-pitch 1.0; show-text "Pitch: Reset"
Ctrl+{ no-osd af-command pitchrb multiply-pitch 0.9438743126816935; show-text "Pitch: Decrease 1 semitone"
Ctrl+} no-osd af-command pitchrb multiply-pitch 1.059463094352953; show-text "Pitch: Increase 1 semitone"

# Seek
HOME seek 0 absolute
END seek 101 absolute-percent
< cycle-values play-direction + -

# OSD
O no-osd cycle-values osd-level 1 2 3 # cycle through OSD mode

# Dual Mono to Mono
Shift+Ctrl+A no-osd af toggle "lavfi=[pan=1c|c0=c0]"; show-text "Dual Mono L to Mono filter"
